//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskkiller {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Taskkiller.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The datafolder with the configuration of Taskkiller will be DELETED!
        ///Press &quot;Yes&quot;, to continue or &quot;No&quot;, to abort. ähnelt.
        /// </summary>
        internal static string MsgBox_ConfigDelete_Text {
            get {
                return ResourceManager.GetString("MsgBox_ConfigDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning! ähnelt.
        /// </summary>
        internal static string MsgBox_ConfigDelete_Title {
            get {
                return ResourceManager.GetString("MsgBox_ConfigDelete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The datafolder could not be created.
        ///Taskkiller will exit now. More information:  ähnelt.
        /// </summary>
        internal static string MsgBox_Error_CD {
            get {
                return ResourceManager.GetString("MsgBox_Error_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file could not be deleted. More information:  ähnelt.
        /// </summary>
        internal static string MsgBox_Error_FileDelete {
            get {
                return ResourceManager.GetString("MsgBox_Error_FileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file to show does not exist. ähnelt.
        /// </summary>
        internal static string MsgBox_Error_FileToShow_NotExisting {
            get {
                return ResourceManager.GetString("MsgBox_Error_FileToShow_NotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taskkiller could not read the configfile.
        ///Taskkiller will exit now. More information:  ähnelt.
        /// </summary>
        internal static string MsgBox_Error_ReadConfigFile {
            get {
                return ResourceManager.GetString("MsgBox_Error_ReadConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The configuration was not complete. Ignoring. ähnelt.
        /// </summary>
        internal static string MsgBox_Error_ReadConfigFile1 {
            get {
                return ResourceManager.GetString("MsgBox_Error_ReadConfigFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error! ähnelt.
        /// </summary>
        internal static string MsgBox_Error_Title {
            get {
                return ResourceManager.GetString("MsgBox_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taskkiller could not create its datafolder.
        ///Taskkiller will exit now. More information:  ähnelt.
        /// </summary>
        internal static string MsgBox_Error_TKiller_Data {
            get {
                return ResourceManager.GetString("MsgBox_Error_TKiller_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taskkiller could not write the configfile.
        ///Taskkiller will exit now. More information:  ähnelt.
        /// </summary>
        internal static string MsgBox_Error_WriteConfigFile {
            get {
                return ResourceManager.GetString("MsgBox_Error_WriteConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It looks like you want to uninstall Taskkiller. Press &quot;Yes&quot;, to delete Taskkiller completely or &quot;No&quot;, to abort. ähnelt.
        /// </summary>
        internal static string MsgBox_ExecutableDelete_Text {
            get {
                return ResourceManager.GetString("MsgBox_ExecutableDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Taskkiller? ähnelt.
        /// </summary>
        internal static string MsgBox_ExecutableDelete_Title {
            get {
                return ResourceManager.GetString("MsgBox_ExecutableDelete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You started Taskkiller the first Time.
        ///You should start the configuration now. ähnelt.
        /// </summary>
        internal static string MsgBox_FirstStart_Text {
            get {
                return ResourceManager.GetString("MsgBox_FirstStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to Taskkiller ähnelt.
        /// </summary>
        internal static string MsgBox_FirstStart_Title {
            get {
                return ResourceManager.GetString("MsgBox_FirstStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You did not enter a processname to add or change. ähnelt.
        /// </summary>
        internal static string MsgBox_NoInput_Text {
            get {
                return ResourceManager.GetString("MsgBox_NoInput_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Input! ähnelt.
        /// </summary>
        internal static string MsgBox_NoInput_Title {
            get {
                return ResourceManager.GetString("MsgBox_NoInput_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You did not select a processname from the list to delete. ähnelt.
        /// </summary>
        internal static string MsgBox_NoSelection_Text {
            get {
                return ResourceManager.GetString("MsgBox_NoSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No selection! ähnelt.
        /// </summary>
        internal static string MsgBox_NoSelection_Title {
            get {
                return ResourceManager.GetString("MsgBox_NoSelection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to abort?
        ///Your changes will not be saved. ähnelt.
        /// </summary>
        internal static string MsgBox_Question_Abort_Text {
            get {
                return ResourceManager.GetString("MsgBox_Question_Abort_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abort? ähnelt.
        /// </summary>
        internal static string MsgBox_Question_Abort_Title {
            get {
                return ResourceManager.GetString("MsgBox_Question_Abort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to exit Taskkiller?
        ///Your changes will not be saved. ähnelt.
        /// </summary>
        internal static string MsgBox_Question_Exit_Text {
            get {
                return ResourceManager.GetString("MsgBox_Question_Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit? ähnelt.
        /// </summary>
        internal static string MsgBox_Question_Exit_Title {
            get {
                return ResourceManager.GetString("MsgBox_Question_Exit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You did not enter any processnames. Do you want to exit Taskkiller? ähnelt.
        /// </summary>
        internal static string MsgBox_Question_NoTasks_Text {
            get {
                return ResourceManager.GetString("MsgBox_Question_NoTasks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is nothing to do! ähnelt.
        /// </summary>
        internal static string MsgBox_Question_NoTasks_Title {
            get {
                return ResourceManager.GetString("MsgBox_Question_NoTasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to start this program? It may contain dangerous viruses! ähnelt.
        /// </summary>
        internal static string MsgBox_Troll_0 {
            get {
                return ResourceManager.GetString("MsgBox_Troll_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t feel like :-P ähnelt.
        /// </summary>
        internal static string MsgBox_Troll_DontFeelLike {
            get {
                return ResourceManager.GetString("MsgBox_Troll_DontFeelLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abort ähnelt.
        /// </summary>
        internal static string String_Abort {
            get {
                return ResourceManager.GetString("String_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add/Edit ähnelt.
        /// </summary>
        internal static string String_AddEdit {
            get {
                return ResourceManager.GetString("String_AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Added processes ähnelt.
        /// </summary>
        internal static string String_AddedProcesses {
            get {
                return ResourceManager.GetString("String_AddedProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose automatically ähnelt.
        /// </summary>
        internal static string String_AutoLang {
            get {
                return ResourceManager.GetString("String_AutoLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        internal static string String_ChooseLang {
            get {
                return ResourceManager.GetString("String_ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure ähnelt.
        /// </summary>
        internal static string String_Config {
            get {
                return ResourceManager.GetString("String_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration ähnelt.
        /// </summary>
        internal static string String_Configuration {
            get {
                return ResourceManager.GetString("String_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete datafolder ähnelt.
        /// </summary>
        internal static string String_DeleteData {
            get {
                return ResourceManager.GetString("String_DeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End it after: ähnelt.
        /// </summary>
        internal static string String_EndAfter {
            get {
                return ResourceManager.GetString("String_EndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string String_Exit {
            get {
                return ResourceManager.GetString("String_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hi, I&apos;m here now! ähnelt.
        /// </summary>
        internal static string String_Hello {
            get {
                return ResourceManager.GetString("String_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide icon in Taskbar ähnelt.
        /// </summary>
        internal static string String_HideIcon {
            get {
                return ResourceManager.GetString("String_HideIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kill process immediately ähnelt.
        /// </summary>
        internal static string String_KillCompletely {
            get {
                return ResourceManager.GetString("String_KillCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other ähnelt.
        /// </summary>
        internal static string String_Other {
            get {
                return ResourceManager.GetString("String_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process: ähnelt.
        /// </summary>
        internal static string String_Process {
            get {
                return ResourceManager.GetString("String_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program ähnelt.
        /// </summary>
        internal static string String_Program {
            get {
                return ResourceManager.GetString("String_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        internal static string String_Remove {
            get {
                return ResourceManager.GetString("String_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string String_Save {
            get {
                return ResourceManager.GetString("String_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a cell and press &quot;Remove&quot; ähnelt.
        /// </summary>
        internal static string String_SelectRemove {
            get {
                return ResourceManager.GetString("String_SelectRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show file in Explorer ähnelt.
        /// </summary>
        internal static string String_ShowInExplorer {
            get {
                return ResourceManager.GetString("String_ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taskkiller Configuration ähnelt.
        /// </summary>
        internal static string String_Title {
            get {
                return ResourceManager.GetString("String_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML-Options ähnelt.
        /// </summary>
        internal static string String_XMLOptions {
            get {
                return ResourceManager.GetString("String_XMLOptions", resourceCulture);
            }
        }
    }
}
